"""Builds the Reticulum configuration file from FireFly's settings.

FireFly keeps its own Reticulum config directory so it never clobbers a
config you wrote by hand for rnsd. Set managed_config = False to use the
system ~/.reticulum instead.
"""
import glob
import os

HEADER = """# ---------------------------------------------------------------
# Generated by FireFly from settings.json on every start.
# Edits here are overwritten. Change settings in the app instead,
# or set "managed_config": false to use ~/.reticulum.
# ---------------------------------------------------------------
"""


def serial_ports():
    """USB serial devices, stable /dev/serial/by-id names first."""
    seen, out = set(), []
    for p in sorted(glob.glob("/dev/serial/by-id/*")):
        real = os.path.realpath(p)
        if real not in seen:
            seen.add(real)
            out.append(p)
    for p in sorted(glob.glob("/dev/ttyUSB*") + glob.glob("/dev/ttyACM*")):
        if os.path.realpath(p) not in seen:
            seen.add(os.path.realpath(p))
            out.append(p)
    return out


def resolve_port(setting, log=print):
    """The chosen port if it exists; otherwise the first USB serial device found.
    (A saved /dev/ttyACM0 can come back as /dev/ttyACM1 after a replug.)"""
    if setting and setting != "auto":
        if os.path.exists(setting):
            return setting
        ports = serial_ports()
        if ports:
            log(f"saved radio port {setting} not found; using {ports[0]}")
            return ports[0]
        return None
    ports = serial_ports()
    return ports[0] if ports else None


def _yn(b): return "Yes" if b else "No"


def build_config(settings, rnode_port=None):
    s = settings
    lines = [HEADER, "[reticulum]",
             f"  enable_transport = {_yn(s['transport'])}",
             f"  share_instance = {_yn(s['share_instance'])}",
             "  panic_on_interface_error = No",
             "", "[logging]", f"  loglevel = {int(s['log_level'])}", "", "[interfaces]"]

    lines += ["", "  [[Local network (AutoInterface)]]",
              "    type = AutoInterface",
              f"    enabled = {_yn(s['auto_interface'])}"]

    # The LoRa radio is NOT configured here: FireFly's radio manager attaches
    # whichever RNode it finds at runtime, so a missing or faulty radio never
    # affects start-up.

    for i, peer in enumerate(s["tcp_peers"]):
        host, _, port = str(peer).rpartition(":")
        if not host or not port.isdigit():
            continue
        lines += ["", f"  [[TCP peer {i + 1}]]",
                  "    type = TCPClientInterface",
                  "    enabled = Yes",
                  f"    target_host = {host}",
                  f"    target_port = {int(port)}"]
    return "\n".join(lines) + "\n"


def write_config(settings, config_dir, rnode_port=None):
    os.makedirs(config_dir, exist_ok=True)
    path = os.path.join(config_dir, "config")
    with open(path, "w", encoding="utf-8") as f:
        f.write(build_config(settings, rnode_port))
    return path
